add new rules for backend
Byndyusoft/eslint-config pull request #35
Opened 2022-09-08 12:10 UTC by Fun795

2022-09-10 05:22 UTC, KillWolfVlad requested changes

2022-09-10 05:22 UTC, KillWolfVlad commented on package.json
> +    "eslint": "^8.22.0",
update ESLint in peerDependencies too

2022-09-10 05:22 UTC, KillWolfVlad commented on typescript-style-backend.js
> +                camelcase: [
This case doesn't work:

```typescript
export class A {
  public UPPERCASE(): void {
    console.log("1");
  }
}

export class B extends A {
  public constructor() {
    super();
    this.UPPERCASE();
  }
}
```

and

```typescript
export class A {
  public UPPERCASEFIELD = 0;
}

export class B extends A {
  public constructor() {
    super();
    console.log(this.UPPERCASEFIELD);
  }
}
```

2022-09-10 05:22 UTC, KillWolfVlad commented on typescript-style-backend.js
> +                'no-underscore-dangle': [
The error occurs during the call, not during the declaration.

![image](https://user-images.githubusercontent.com/18448635/189470390-3c72b8e4-2833-4870-a6fc-d75fe8e54910.png)

2022-09-10 05:55 UTC, KillWolfVlad commented
I think better use https://typescript-eslint.io/rules/naming-convention rule

```patch
diff --git a/typescript-style-backend.js b/typescript-style-backend.js
index 1598c18..a657987 100644
--- a/typescript-style-backend.js
+++ b/typescript-style-backend.js
@@ -108,6 +108,12 @@ module.exports = {
                     {
                         selector: 'enumMember',
                         format: ['camelCase']
+                    },
+                    {
+                        selector: ['classProperty', 'classMethod', 'parameterProperty'],
+                        format: ['camelCase'],
+                        leadingUnderscore: 'forbid',
+                        trailingUnderscore: 'forbid'
                     }
                 ],
                 // @typescript-eslint/eslint-plugin Extension Rules
```

2022-09-12 08:32 UTC, Fun795 commented on package.json
> +    "eslint": "^8.22.0",
updated

2022-09-12 08:32 UTC, Fun795 commented on typescript-style-backend.js
> +                camelcase: [
add rules for class method

2022-09-14 09:43 UTC, KillWolfVlad requested changes
> feat: add new rules

Please, use more specific message

2022-09-23 13:01 UTC, KillWolfVlad approved these changes

2022-09-23 13:04 UTC, merged