docs: update README.md
Byndyusoft/eslint-config pull request #40
Opened 2022-09-29 11:54 UTC by Fun795

2022-09-30 12:23 UTC, codesprut approved these changes

2022-10-01 06:18 UTC, KillWolfVlad requested changes
Add rest configs in README (e.g. javascript, header-apache-2.0)

2022-10-01 06:18 UTC, KillWolfVlad commented on README.md
> +- [@KillWolfVlad](https://github.com/KillWolfVlad)
Please add @sadcitizen as maintainer too

2022-10-03 04:30 UTC, step1989 approved these changes

2022-10-03 12:53 UTC, Fun795 commented on README.md
> +- [@KillWolfVlad](https://github.com/KillWolfVlad)
done

2022-10-08 07:09 UTC, KillWolfVlad approved these changes

2022-10-08 07:14 UTC, merged