Next
Byndyusoft/eslint-config pull request #57
Opened 2023-09-03 07:05 UTC by KillWolfVlad

Fix #38 
Fix #52

2023-09-03 15:30 UTC, sadcitizen requested changes
Зачем надо было менять npm на yarn?

2023-09-03 15:30 UTC, sadcitizen commented on .prettierrc.yaml
> +trailingComma: all
Забери настройки форматирования из старого файла .prettierrc.

2023-09-03 15:30 UTC, sadcitizen commented on README.md
>  - [@KillWolfVlad](https://github.com/KillWolfVlad)
Забавная сортировка мейнтейнеров.

2023-09-03 15:30 UTC, sadcitizen commented on .editorconfig
> +indent_size = 2
4

2023-09-03 15:30 UTC, sadcitizen commented on configs/react.js
> +/*
Отличный пример того, как форматирование сделало кодревью максимально сложными.

2023-09-04 04:00 UTC, KillWolfVlad commented on README.md
>  - [@KillWolfVlad](https://github.com/KillWolfVlad)
Сортировку мейнтейнеров не менял

2023-09-04 04:02 UTC, KillWolfVlad commented on configs/react.js
> +/*
Форматирование поменялось только в 3a67c0a16cbed70d268dd6cd0ff34f1d253cbc5e, никаких изменений в правилах в этом коммите нет.

2023-09-04 04:02 UTC, KillWolfVlad commented on .prettierrc.yaml
> +trailingComma: all
Все наши OpenSource проекты должны следовать единым стандартам форматирования, которые заданы в https://github.com/Byndyusoft/node-base-template

2024-04-10 10:57 UTC, sadcitizen commented on .prettierrc.yaml
> +trailingComma: all
Я не участвовал в разработке этих стандартов. Они нелегитимны и не могут применяться в этому пакету.

2024-04-10 10:58 UTC, sadcitizen commented on configs/react.js
> +/*
Комментарий был написан к PR, а не к коммиту

2024-07-02 09:36 UTC, closed without merging