feat!: upgrade all the deps, support for TS 5, NodeJS 22, new rules
Byndyusoft/eslint-config pull request #59
Opened 2024-06-19 13:53 UTC by vglebovich-lmru

## Objectives

1. TypeScript 5 support
2. NodeJS 22 support
3. New linting rules
4. Reducing the number of packages flagged as vulnerable (improving our security metrics)
5. Reducing the number of "dismatch peer dependency version" warnings

## Impact

Considering the following points, in my opinion it's reasonable to release this as a major version

1. May introduce breaking changes due to new enforced linting rules
2. Minimal supported NodeJS version raised to `^18.18.0` by `@typescript-eslint/parser`
3. Minimal supported ESLint version raised to `^8.56.0` by `@typescript-eslint/parser`
4. TypeScript 4 is still supported

## Changes

1. Updated minimum supported `eslint` version from `^8.13.0` to `^8.57.0` (range `>=8.57.0 <9.0.0`)
6. Upgraded `eslint-plugin-sonarjs` from `^0.13.0` to `^1.0.3` with minor configuration adjustments
7. Updated all remaining dependencies to their latest versions
8. Revised `README.md` to reflect new `eslint` version requirements

2024-06-19 13:58 UTC, vglebovich-lmru commented
@KillWolfVlad, @sadcitizen, please, take a look

2024-06-19 23:32 UTC, vglebovich-lmru commented
I'd like to discuss with you disabling some rules after trying them on our repos:

1. [`n/no-sync`](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-sync.md): Too primitive detector, a lot of false positivies on something suffixed with "Sync", not even called
2. [`unicorn/prefer-top-level-await`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-top-level-await.md): Requires scripts to be modules, which isn't reasonable for the most of cases with shared packages in NodeJS
3. [`@typescript-eslint/no-unsafe-enum-comparison`](https://typescript-eslint.io/rules/no-unsafe-enum-comparison/#options): Enums are widely misused in the TS community, so it leads to too many valid cases being flagged

2024-06-22 10:28 UTC, sadcitizen approved these changes

2024-06-24 05:35 UTC, KillWolfVlad requested changes

2024-06-24 05:35 UTC, KillWolfVlad commented on package.json
> +    "husky": "^9.0.11",
husky был обновлен, но пре коммит скрипты не были перенесены по гайду https://typicode.github.io/husky/migrate-from-v4.html

2024-06-24 05:35 UTC, KillWolfVlad commented on typescript-style-backend.js
> +                '@typescript-eslint/no-unsafe-enum-comparison': 'off'
Почему была выключено это рекомендованное правило? Оно кажется весьма полезным, т.к. заставляет использовать enum-ы правильно.

2024-06-24 05:35 UTC, KillWolfVlad commented on node.js
> +        'n/no-sync': 'off'
Правило кажется полезным - просто так что-то с суффиксом sync лучше не вызывать, чтобы не блокировать io.

2024-06-24 10:01 UTC, vglebovich-lmru commented on typescript-style-backend.js
> +                '@typescript-eslint/no-unsafe-enum-comparison': 'off'
IMO enum-ы лучше избегать совсем, и никто их не использует правильно. Literal union и Key-value as const object более лучшие альтернативы и предназначены для разных кейсов.

У нас в кодовой базе очень много вполне валидных кейсов, большинство из которых это сравнение `res.status` (number) из axios с `HttpStatus` (enum) из NestJS

2024-06-24 10:22 UTC, vglebovich-lmru commented on node.js
> +        'n/no-sync': 'off'
Слишком примитивный детектор -- детектит всё с суффиксом -Sync. Вероятно, имеет смысл смирится и переименовать всё в кодовой базе чтобы оставить рул включённым

2024-06-24 10:39 UTC, vglebovich-lmru commented on package.json
> +    "husky": "^9.0.11",
Исправил

2024-06-25 10:44 UTC, KillWolfVlad commented on node.js
> +        'n/no-sync': 'off'
У нас разве используются методы с суффиксом -Sync?

2024-06-25 10:46 UTC, KillWolfVlad commented on typescript-style-backend.js
> +                '@typescript-eslint/no-unsafe-enum-comparison': 'off'
>  большинство из которых это сравнение res.status (number) из axios с HttpStatus (enum) из NestJS

Вот это да. Давай тогда его оставим выключенным.

2024-06-25 10:57 UTC, KillWolfVlad commented on node.js
> +        'n/no-sync': 'off'
Правило реагирует не только на методы, но и названия переменных. Лучше выключить.

2024-06-25 10:57 UTC, KillWolfVlad approved these changes

2024-06-25 11:39 UTC, merged